matrix:
    include:
        # test
        -   os: linux
            language: node_js
            node_js:
                - 8

            cache:
                yarn: true
                directories:
                    - node_modules

            install:
                - yarn --version
                - yarn install
            script:
                - yarn test

        # android
        -   if: branch =~ ^master OR branch =~ /^pr\..*/
            os: linux
            language: android
            jdk: oraclejdk8

            cache:
                yarn: true
                directories:
                    - node_modules

            before_install:
                - echo y | android update sdk --no-ui --filter build-tools-26.0.1,build-tools-26.0.2,android-26,extra-android-m2repository
            install:
                - nvm install 8
                - yarn --version
                - yarn install
            android:
                components:
                    - tools
                    - platform-tools
                    # android 23
                    - build-tools-23.0.1
                    - build-tools-25.0.1
                    - build-tools-26.0.1
                    - build-tools-26.0.2
                    - android-23
                    # extra
                    - extra-android-m2repository
                    - extra-google-google_play_services
                    - extra-google-m2repository
                    - addon-google_apis-google-16
                licenses:
                    - 'android-sdk-preview-license-.+'
                    - 'android-sdk-license-.+'
                    - 'google-gdk-license-.+'
            script:
                - yarn build:android
            #deploy:
            #   skip_cleanup: true
            #   provider: releases
            #   api_key:
            #       secure: XXX=
            #   file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk
            #   on:
            #       repo: demokratie-live/democracy-client
            #       tags: true

        # ios
        -   if: branch =~ ^master OR type =~ ^pull_request
            osx_image: xcode9
            language: objective-c

            cache:
                yarn: true
                directories:
                    - node_modules

            install:
               - nvm install 8
               - npm install -g yarn
               - yarn --version
               - yarn install

            script:
                - cd ios
                - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios beta
after_script:
  - echo "BUILD FINISHED"