matrix:
    include:
        # test
        -   os: linux
            language: node_js
            node_js:
                - 8
            install:
                - yarn --version
                - yarn install
            script:
                - yarn test:eslint
        # web
        -   os: linux
            language: node_js
            node_js:
                - 8
            install:
                - yarn --version
                - yarn install
            script:
                - yarn build:web
        # android
        -   os: linux
            language: android
            jdk: oraclejdk8
            before_install:
                - echo "$ANDROID_HOME"
                - mkdir "$ANDROID_HOME/licenses" || true
                - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
                - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
            install:
                - nvm install 8
                - yarn --version
                - yarn install
            android:
                components:
                    - tools
                    - platform-tools
                    # android 23
                    - build-tools-23.0.1
                    - build-tools-26.0.1
                    - android-23
                    # extra
                    - extra-android-m2repository
                    - extra-google-google_play_services
                    - extra-google-m2repository
                    - addon-google_apis-google-16
                licenses:
                    - android-sdk-preview-license-.+
                    - android-sdk-license-.+
                    - google-gdk-license-.+
            script:
                - chmod +x ./android/gradlew && yarn build:android
            #deploy:
            #   skip_cleanup: true
            #   provider: releases
            #   api_key:
            #       secure: XXX=
            #   file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk
            #   on:
            #       repo: demokratie-live/democracy-client
            #       tags: true
        # ios
        #-   os: osx
        #    osx_image: xcode9
        #    language: objective-c
        #    install:
        #        - nvm install 8
        #        - yarn --version
        #        - yarn install
        #    xcode_project: ios/democracyclient.xcodeproj
        #    xcode_scheme: ios/democracyclientTests
        #    script:
        #        - yarn build:ios
        #        #- xctool run-tests -scheme PepperoniAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
after_script:
  - echo "BUILD FINISHED"