language: android
before_install:
- nvm install 6
- node --version
install:
- yarn install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
  - yarn eslint
  - yarn build:web
  #- cd android && chmod +x ./gradlew && ./gradlew assembleRelease
  - chmod +x ./android/gradlew && yarn build:android
deploy:
  skip_cleanup: true
  provider: releases
  #api_key:
  #  secure: XXX=
  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk
  on:
    repo: demokratie-live/democracy-client
    tags: true
after_script:
  - echo "BUILD FINISHED"