language: objective-c
os: osx
before_install:
- nvm install
- node --version
install:
- yarn install
xcode_project: ios/democracyclient.xcodeproj
xcode_scheme: ios/democracyclientTests
script:
  - cd ios && xcodebuild -scheme democracyclient -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool run-tests -scheme PepperoniAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
#deploy:
#  skip_cleanup: true
#  provider: releases
#  #api_key:
#  #  secure: XXX=
#  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk
#  on:
#    repo: demokratie-live/democracy-client
#    tags: true
after_script:
  - echo "BUILD FINISHED"
  
  
  

#      osx_image: xcode8.2
#      node_js: false
#      before_install:
#        - nvm install 7
#        - node --version
#        - travis_retry npm install -g yarn
#        - yarn -version
#      install:
#        - travis_retry gem install xcpretty
#        - travis_retry yarn
      
#      script:
#        - cd ios
#        - xcodebuild -scheme PepperoniAppTemplate -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#        - travis_retry xctool run-tests -scheme PepperoniAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO