cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - packages/mobile-app/node_modules
    - packages/mobile-ui/node_modules
# notifications:
#   email:
#     on_success: never
#     on_failure: always

matrix:
  include:
    - language: swift
      os: osx
      osx_image: xcode11.1
      if: sender != "Travis CI"
      node_js: false
      before_install:
        - nvm install 10
        - node --version
        - npm install -g yarn
        - yarn -version
        - gem install fastlane
        - echo -e "machine github.com\n  login $GITHUB_API_TOKEN" >> ~/.netrc
      install:
        - yarn
        - yarn pods
        - cd packages/mobile-app/ios
        - bundle install
        - cd $TRAVIS_BUILD_DIR
      script:
        - cd packages/mobile-app/ios
        - bundle exec fastlane ios beta
        - cd $TRAVIS_BUILD_DIR
      after_success:
        - .travis/push.sh
