language: objective-c
os: osx
install:
- nvm install
- node --version
- yarn --version
- yarn install
xcode_project: ios/democracyclient.xcodeproj
xcode_scheme: ios/democracyclientTests
script:
  - cd ios && xcodebuild -scheme democracyclient -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool run-tests -scheme PepperoniAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
after_script:
  - echo "BUILD FINISHED"

#      osx_image: xcode8.2
#      node_js: false
#      before_install:
#        - nvm install 7
#        - travis_retry npm install -g yarn
#        - yarn -version
#      install:
#        - travis_retry gem install xcpretty
#        - travis_retry yarn
#      script:
#        - cd ios
#        - xcodebuild -scheme PepperoniAppTemplate -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
#        - travis_retry xctool run-tests -scheme PepperoniAppTemplate -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO