env:
  global:
    secure: "n6fpr7pt7ZJce03YQ28aoLUMiGCs3+5ruOyd27IOj1WLnKQxBg+Bdr6Kq+kANxLwGP7xPMR9gUMjCvhmXYXFgK+qTY8LC2ZV3XBOTHO6xqEnzDQUI/i2kfT/4OR42Cnctu65p9IcA1N8kqEBd9Z9hSjqB7fMr94R5bz+A1zu50hjgHD3ro/4ov5EjF9jF5DCtSqfk0uqBBvKuMpsaMeKY6YXhLhhhmcWZmQT+uXBeloH5oU0zFIrDWbgiFygxCW8+rcoW9jfMiRDU8FI6qXj6RVHIHTiqv0XtEDEUh4TFpj3MB+2NVeUqL2BcOS7R+eLlWus04wYeuBLCr6BzdHNDLamno4iDobR5gjIpZcUGQcDeMYSDl9XKvZsWVwgfd8EqshO6L8f0JXoOZPdqeGjrTpePjeGkWHabNqgBeL+lKy8xFdoxPUhZzy6aFAXqJaxow/wXPuxY9QdJwNXsVysTUvR/pn5Ngh/q9FIxM3yMPCOX+/d4JfM4R8j6Uw4tnZK4XIlo2l8dYt4pGvMjw7ojJVGz0Kx1PNfwsimaZi9MkKBGXLE8k0+GxTUC/sa0AL5kJhLt7Xl67qwCwdRnOj9k85w8a6y4/Pf5xjA/QQ2WD3RaOj9Y1NqVG0phB+m0ZLflIXqAFEQ+kEeW6WmBYgkFaff9L3llTP2RVginOi0e8M="
matrix:
  include:
  # test
  - os: linux
    language: node_js
    node_js:
    - 8

    cache:
      yarn: true
      directories:
      - node_modules

    install:
    - yarn --version
    - yarn install
    script:
    - yarn test

  # android test
  - if: type IN (pull_request)
    os: linux
    language: android
    jdk: oraclejdk8

    cache:
      yarn: true

    before_install:
    - echo y | android update sdk --no-ui --filter build-tools-26.0.1,build-tools-26.0.2,android-26,extra-android-m2repository   
    - openssl aes-256-cbc -K $encrypted_51873ec394c3_key -iv $encrypted_51873ec394c3_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet

    install:
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
                    # android 23
      - build-tools-23.0.1
      - build-tools-25.0.1
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
                    # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
                    - 'android-sdk-preview-license-.+'
                    - 'android-sdk-license-.+'
                    - 'google-gdk-license-.+'
    script:
    - cd android
    - fastlane android test

  # ios test
  - if: type IN (pull_request)
    osx_image: xcode9.2
    language: objective-c

    cache:
      bundler: true
      yarn: true
      cocoapods: true

    install:
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install

    script:
    - fastlane update_fastlane
    - cd ios
    - bundle exec fastlane ios test

  # android  deploy Alpha
  #- if: branch =~ ^master AND NOT type =~ ^pull_request
  - os: linux
    language: android
    jdk: oraclejdk8

    cache:
      yarn: true

    before_install:
    - echo y | android update sdk --no-ui --filter build-tools-26.0.1,build-tools-26.0.2,android-26,extra-android-m2repository   
    - openssl aes-256-cbc -K $encrypted_51873ec394c3_key -iv $encrypted_51873ec394c3_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet

    install:
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
      # android 23
      - build-tools-23.0.1
      - build-tools-25.0.1
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
      # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
                    - 'android-sdk-preview-license-.+'
                    - 'android-sdk-license-.+'
                    - 'google-gdk-license-.+'
    script:
    - cd android && fastlane android alpha
    after_success:
       - "curl -H 'Content-Type: application/json'  -X POST -d \"{\\\"content\\\":\\\"SUCCESS: New Android Alpha Version $TRAVIS_BUILD_NUMBER available!\\\"}\" ${DISCORD_WEBHOOK}"
    after_failure:
       - "curl -H 'Content-Type: application/json'  -X POST -d \"{\\\"content\\\":\\\"FAILURE: Deploying new Android Alpha Version $TRAVIS_BUILD_NUMBER failed!\\\"}\" ${DISCORD_WEBHOOK}"

  # ios deploy Testflight
  - if: branch =~ ^master AND NOT type =~ ^pull_request
    osx_image: xcode9.2
    language: objective-c
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests

    cache:
      bundler: yes
      yarn: true

    before_install:
    - openssl aes-256-cbc -K $encrypted_51873ec394c3_key -iv $encrypted_51873ec394c3_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar

    install:
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install

    script:
    - fastlane update_fastlane
    - cd ios
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios beta
    - "curl -H 'Content-Type: application/json'  -X POST -d '{\"content\":\"Neue iOS TestFlight Version verfügbar!\"}' ${DISCORD_WEBHOOK}"

after_script:
- echo "BUILD FINISHED"
