cache:
  yarn: true
  directories:
    - node_modules
    - packages/mobile-app/node_modules
    - packages/mobile-ui/node_modules

install:
  - yarn

matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.1
      script: .travis/ci_ios.sh
    - language: android
      android:
        components:
          - tools
          - platform-tools
      sudo: true
      script: .travis/ci_android.sh
