matrix:
  include:
    - os: osx
      language: swift
      osx_image: xcode11.1
      script: .travis/ci_ios.sh
    - language: android
      android:
        components:
          - tools
          - platform-tools
      sudo: true
      script: .travis/ci_android.sh
