matrix:
  include:
        # test
  - os: linux
    language: node_js
    node_js:
    - 8

    cache:
      yarn: true
      directories:
      - node_modules

    install:
    - yarn --version
    - yarn install
    script:
    - yarn test

        # android test
  - if: branch =~ /^pr\..*/
    os: linux
    language: android
    jdk: oraclejdk8

    cache:
      yarn: true
      directories:
      - node_modules

    before_install:
    - echo y | android update sdk --no-ui --filter build-tools-26.0.1,build-tools-26.0.2,android-26,extra-android-m2repository   
    - openssl aes-256-cbc -K $encrypted_b05ee5be06d5_key -iv $encrypted_b05ee5be06d5_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet

    install:
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
                    # android 23
      - build-tools-23.0.1
      - build-tools-25.0.1
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
                    # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
                    - 'android-sdk-preview-license-.+'
                    - 'android-sdk-license-.+'
                    - 'google-gdk-license-.+'
    script:
    - cd android
    - fastlane android test

  # ios test
  - if: branch =~ /^pr\..*/
    osx_image: xcode9
    language: objective-c

    cache:
      yarn: true
      directories:
      - node_modules

    install:
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install

    script:
    - fastlane update_fastlane
    - cd ios
    - bundle exec fastlane ios test

        # android  deploy Alpha
  - if: branch =~ ^master AND NOT type =~ ^pull_request
    os: linux
    language: android
    jdk: oraclejdk8

    cache:
      yarn: true
      directories:
      - node_modules

    before_install:
    - echo y | android update sdk --no-ui --filter build-tools-26.0.1,build-tools-26.0.2,android-26,extra-android-m2repository   
    - openssl aes-256-cbc -K $encrypted_b05ee5be06d5_key -iv $encrypted_b05ee5be06d5_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - gem update --system
    - gem install fastlane --no-rdoc --no-ri --no-document --quiet

    install:
    - nvm install 8
    - yarn --version
    - yarn install
    android:
      components:
      - tools
      - platform-tools
                    # android 23
      - build-tools-23.0.1
      - build-tools-25.0.1
      - build-tools-26.0.1
      - build-tools-26.0.2
      - android-23
                    # extra
      - extra-android-m2repository
      - extra-google-google_play_services
      - extra-google-m2repository
      - addon-google_apis-google-16
      licenses:
                    - 'android-sdk-preview-license-.+'
                    - 'android-sdk-license-.+'
                    - 'google-gdk-license-.+'
    script:
    - cd android
    - fastlane android alpha

  # ios deploy Testflight
  - if: branch =~ ^master AND NOT type =~ ^pull_request
    osx_image: xcode9
    language: objective-c

    cache:
      yarn: true
      directories:
      - node_modules

    install:
    - nvm install 8
    - npm install -g yarn
    - yarn --version
    - yarn install

    script:
    - fastlane update_fastlane
    - cd ios
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" bundle exec fastlane ios beta
after_script:
- echo "BUILD FINISHED"
