# environment setup
language: swift
osx_image: xcode11.2

install:
  - yarn && yarn pods
  - cd packages/mobile-app/ios
  - bundle install
jobs:
  include:
    - stage: Deploy
      name: Deploy to App Store
      script:
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane beta
      if: branch =~ /^release\/.*$/
