name: Linting project

on: [push]

jobs:
    lint:
        name: Lint Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - run: yarn install

            - name: Run ESLint on UI
              run: yarn workspace @democracy-deutschland/mobile-ui lint:eslint
            - name: Run TSLint on UI
              run: yarn workspace @democracy-deutschland/mobile-ui lint:ts

            - name: Run ESLint on App
              run: yarn workspace app lint:eslint
            - name: Run TSLint on App
              run: yarn workspace app lint:ts

            - uses: stefanzweifel/git-auto-commit-action@v4.1.2
              with:
                  commit_message: Action – commit autofix changes

    build-ios:
        name: Build ios
        # needs: lint
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - run: yarn install
              working-directory: packages/mobile-app

            - run: pod install
              working-directory: packages/mobile-app/ios

            # install fastlane dependencies
            - run: gem install bundler:1.17.3

            - name: Fastlane
              uses: maierj/fastlane-action@v1.4.0
              with:
                  lane: "ios beta"
                  subdirectory: "packages/mobile-app/ios"
              env:
                  TRAVIS_BRANCH: alpha
                  TRAVIS: "true"
                  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
