name: Linting project

on: [push]

jobs:
    build:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - run: yarn install

            - name: Run ESLint on UI
              run: yarn workspace @democracy-deutschland/mobile-ui lint:eslint
            - name: Run ESLint on App
              run: yarn workspace app lint:eslint
            - uses: stefanzweifel/git-auto-commit-action@v4.1.2
              with:
                  commit_message: Apply automatic changes
