name: Linting project

on: [push]

jobs:
    build:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - uses: actions/cache@v1
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - run: yarn install

            - name: Run ESLint on UI
              run: yarn workspace @democracy-deutschland/mobile-ui lint:es
            - name: Run ESLint on App
              run: yarn workspace app lint
            - uses: stefanzweifel/git-auto-commit-action@v4.1.2
              with:
                  commit_message: Apply automatic changes
