name: Lint

on:
  push:
    branches-ignore:
      - internal
      - alpha
      - beta
      - master

jobs:
  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - run: yarn install
        working-directory: packages/mobile-app

      - name: Run ESLint on App
        run: yarn lint:eslint
        working-directory: packages/mobile-app

      - name: Run TSLint on App
        run: yarn lint:ts
        working-directory: packages/mobile-app

      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Action – commit autofix changes
